#!/bin/bash

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

cat /etc/letsencrypt/live/somdomato.com/fullchain.pem /etc/letsencrypt/live/somdomato.com/privkey.pem > /usr/share/icecast2/icecast.pem

chown icecast2:icecast /usr/share/icecast2/icecast.pem

systemctl reload nginx
systemctl restart icecast2 liquidsoap
