#!/bin/bash

set -eu

ERGO_PATH="/usr/share/ergo"

umask 077
cp /etc/letsencrypt/live/irc.somdomato.com/fullchain.pem $ERGO_PATH
cp /etc/letsencrypt/live/irc.somdomato.com/privkey.pem $ERGO_PATH

chown ergo:ergo $ERGO_PATH/*.pem

systemctl reload ergo.service
