FROM oven/bun

WORKDIR /usr/src/app

# Copy the lock and package file
COPY api/bun.lockb . 
COPY api/package.json . 
COPY api/index.ts . 

RUN bun install --frozen-lockfile --production

USER bun

EXPOSE 3000/tcp

ENTRYPOINT [ "bun", "run", "index.ts" ]